// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ISsKFGnPj8nJDUAVtoLbg1Rr5IdJL54',
    appId: '1:658348253972:web:aa57ac8e8103aabfc81801',
    messagingSenderId: '658348253972',
    projectId: 'whatsapp-app-95fa7',
    authDomain: 'whatsapp-app-95fa7.firebaseapp.com',
    storageBucket: 'whatsapp-app-95fa7.appspot.com',
    measurementId: 'G-Z1XKGB8XMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBuUDek3DWkFnSOcGEPHLgqae7mLD2Lck',
    appId: '1:658348253972:android:51410e22ce8a0039c81801',
    messagingSenderId: '658348253972',
    projectId: 'whatsapp-app-95fa7',
    storageBucket: 'whatsapp-app-95fa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjtaBplsTwDJA38SfWWS2nY39REJsjGx4',
    appId: '1:658348253972:ios:56f09f57e80d1ac3c81801',
    messagingSenderId: '658348253972',
    projectId: 'whatsapp-app-95fa7',
    storageBucket: 'whatsapp-app-95fa7.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjtaBplsTwDJA38SfWWS2nY39REJsjGx4',
    appId: '1:658348253972:ios:56f09f57e80d1ac3c81801',
    messagingSenderId: '658348253972',
    projectId: 'whatsapp-app-95fa7',
    storageBucket: 'whatsapp-app-95fa7.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4ISsKFGnPj8nJDUAVtoLbg1Rr5IdJL54',
    appId: '1:658348253972:web:c47a28f46f71c5c0c81801',
    messagingSenderId: '658348253972',
    projectId: 'whatsapp-app-95fa7',
    authDomain: 'whatsapp-app-95fa7.firebaseapp.com',
    storageBucket: 'whatsapp-app-95fa7.appspot.com',
    measurementId: 'G-J05VX801P5',
  );
}
